spring.application.name=course-service
# path: course-service/src/main/resources/application.properties
# purpose: cau hinh cong chay va ket noi database cho course-service
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/course_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=24112005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te